name: CI

on: [push, workflow_dispatch, pull_request]

# test
# lint
# build
# release if tags [needs: test, lint, build]
# deploy [needs: release]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run tests
        run: go test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['linux', 'darwin', 'windows']
        arch: ['amd64', 'arm64']
    env:
      OUTPUT_BINARY: hello_${{ matrix.os }}_${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build ${{ matrix.os }}/${{ matrix.arch }}
        run: script/build -o $OUTPUT_BINARY
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: $OUTPUT_BINARY
          if-no-files-found: error
          retention-days: 1
  release:
    runs-on: ubuntu-latest
    needs: [test, lint, build]
    if: startsWith(github.ref, 'refs/tags') # only run when tags pushed
    steps:
      - name: Pretend to release
        run: |
          echo "pretend to run release..."
          sleep 5
          echo "done!"
