name: CI

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Pretend to test
        run: |
          echo "pretend to run tests..."
          sleep 5
          echo "done!"
  release:
      runs-on: ubuntu-latest
      needs: test
      if: startsWith(github.ref, 'refs/tags')
      steps:
        - name: Pretend to test
          run: |
            echo "pretend to run tests..."
            sleep 5
            echo "done!"
