name: CI

on: [push, workflow_dispatch, pull_request]

# test
# build
# lint
# release if tags [needs: test, lint, build] 
# deploy [needs: release]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Pretend to test
        run: |
          echo "pretend to run tests..."
          sleep 5
          echo "done!"
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Pretend to test
          run: |
            echo "pretend to run tests..."
            sleep 5
            echo "done!"
  release:
      runs-on: ubuntu-latest
      needs: test
      if: startsWith(github.ref, 'refs/tags')
      steps:
        - name: Pretend to test
          run: |
            echo "pretend to run tests..."
            sleep 5
            echo "done!"
