name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Prentend to release
        run: |
          echo "pretend to release..."
          sleep 5
          echo "released!"
