name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Pretend to test
        run: |
          echo "pretend to run tests..."
          sleep 5
          echo "done!"
